#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate

/usr/local/bin/gunicorn birthday.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --chdir=/app