# Generated by Django 3.2.7 on 2021-10-01 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Congratulate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bday_name', models.CharField(max_length=128)),
                ('alert_datetime', models.DateTimeField()),
                ('notify_by_email', models.BooleanField(default=True)),
                ('notify_by_push', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
